import type { Job } from '@/lib/types';

export const jobTypes: Job['type'][] = ['全职', '兼职', '合同工'];
export const locations = ['北京', '上海', '广州', '深圳', '成都', '杭州', '重庆', '武汉'];

export const mockJobs: Job[] = [
  {
    id: '1',
    title: '建筑工人',
    company: '中国建筑集团',
    location: '北京',
    salary: '8000-12000元/月',
    type: '全职',
    description: '负责建筑工地的基础施工工作，需要有相关经验，吃苦耐劳。包吃住，有五险一金。',
  },
  {
    id: '2',
    title: '电焊工',
    company: '上海振华重工',
    location: '上海',
    salary: '10000-15000元/月',
    type: '全职',
    description: '需要持证上岗，熟练掌握氩弧焊、二保焊等多种焊接技术。有大型项目经验者优先。',
  },
  {
    id: '3',
    title: '餐厅服务员',
    company: '海底捞火锅',
    location: '广州',
    salary: '5500-7000元/月',
    type: '全职',
    description: '负责点餐、上菜、维护桌面清洁等工作。要求有良好的服务意识和沟通能力。',
  },
  {
    id: '4',
    title: '快递派送员',
    company: '顺丰速运',
    location: '深圳',
    salary: '9000-13000元/月',
    type: '全职',
    description: '负责指定区域内的快递派送和揽收工作，多劳多得，需自备电动车。',
  },
  {
    id: '5',
    title: '工厂操作工',
    company: '比亚迪汽车',
    location: '重庆',
    salary: '5000-7500元/月',
    type: '合同工',
    description: '新能源汽车电池生产线操作，工作环境好，提供免费培训和住宿。',
  },
  {
    id: '6',
    title: '家政保洁',
    company: '天鹅到家',
    location: '杭州',
    salary: '6000-8500元/月',
    type: '全职',
    description: '提供专业的家庭保洁服务，要求细心、有责任心，公司提供专业培训和工具。',
  },
  {
    id: '7',
    title: '木工师傅',
    company: '业之峰装饰',
    location: '北京',
    salary: '11000-16000元/月',
    type: '合同工',
    description: '负责高端住宅及商业空间的室内装修木工部分，要求手艺精湛，能看懂图纸。',
  },
  {
    id: '8',
    title: '仓库管理员',
    company: '京东物流',
    location: '武汉',
    salary: '5500-8000元/月',
    type: '全职',
    description: '负责亚洲一号智能仓的货物入库、出库、盘点及系统操作。要求会使用电脑。',
  },
  {
    id: '9',
    title: '展会临时搭建工',
    company: '广州会展中心',
    location: '广州',
    salary: '300-500元/天',
    type: '兼职',
    description: '负责广交会等大型展会的展位搭建和拆除工作，工作时间集中在展前和展后。',
  },
  {
    id: '10',
    title: '外卖骑手',
    company: '美团外卖',
    location: '上海',
    salary: '10000-18000元/月',
    type: '全职',
    description: '负责商圈内的餐饮外卖配送服务，系统自动派单，时间自由，收入上不封顶。',
  },
];
